project:
  type: website

website:
  title: "Risk and spread of fire"
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - text: Data Analysis
        menu:
        - href: artik.qmd
          text: Artik
        - href: ashotsk.qmd
          text: Ashotsk
        - href: azatan.qmd
          text: Azatan
        - href: gavar.qmd
          text: Gavar
        - href: maralik.qmd
          text: Maralik
        - href: panik.qmd
          text: Panik
        - href: sevan.qmd
          text: Sevan
        - href: vazgen.qmd
          text: Vazgen Sargsyan school
        - href: conclusion.qmd
          text: Conclusion
      - href: sources.qmd
        text: "Sources"
      - about.qmd
  sidebar:
    style: "floating"
    contents:
      - section: "Areas"
        contents:
          - artik.qmd
          - ashotsk.qmd
          - azatan.qmd
          - gavar.qmd
          - maralik.qmd
          - panik.qmd
          - sevan.qmd
          - href: vazgen.qmd
            text: Vazgen Sargsyan school
      - href: conclusion.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



