---
title: "Conclusion"
editor: visual
execute:
  echo: false
---

```{r te44s, message=FALSE, warning=FALSE}
library(tidyverse)
library(dplyr)
artik <- read_csv("artik.csv")
ashotsk <- read_csv("ashotsk.csv")
azatan <- read_csv("azatan.csv")
gavar <- read_csv("gavar.csv")
maralik <- read_csv("maralik.csv")
panik <- read_csv("panik.csv")
sevan <- read_csv("sevan.csv")
vazgen <- read_csv("vazgen.csv")
data <- bind_rows(artik, ashotsk, azatan, gavar, maralik, panik, sevan, vazgen) 

data |> drop_na() |> ggplot(aes(x=temperature, fill=device, color=device)) + geom_density(alpha=0.2) + theme_minimal() + xlim(-25, 50) + labs(fill="Area", color="Area", x="Temperature", y="Density") + scale_fill_manual(values = rainbow(8), labels = c("Vazgen_Sargsyan" = "Vazgen Sargsyan school")) + scale_color_manual(values = rainbow(8), labels = c("Vazgen_Sargsyan" = "Vazgen Sargsyan school"))

```

```{r tes3, message=FALSE, warning=FALSE}
data |> drop_na() |> ggplot(aes(x=humidity, fill=device)) + geom_histogram(binwidth=1) + labs(fill="Area", color="Area", x="Humidity", y="Density") + scale_fill_manual(values=rainbow(8), labels = c("Vazgen_Sargsyan" = "Vazgen Sargsyan school")) + theme_minimal() 
```

```{r tes2, message=FALSE, warning=FALSE}
library(gganimate)
library(hrbrthemes)
library(ggplot2)
library(gifski)

plot <- data |> mutate(humidity_danger=ifelse(humidity < 30 & temperature>30, temperature-humidity, 0), .before=1) |> ggplot(mapping=aes(x=time, y=humidity_danger, group=device, color=device)) + geom_line() + geom_point() + ggtitle("Humidity danger level in different areas") + theme_ipsum() + labs(x="Time", y="Danger level") + transition_reveal(time)

animated_plot <- animate(plot, nframes = 100, fps = 10, renderer = gifski_renderer())

anim_save("humidity_danger_animation.gif", animated_plot)

print(animated_plot)

```
